apiVersion: v1
kind: Pod
metadata:
  name: pamdemo
  labels:
    app: pamdemo
spec:
  containers:
  - name: pamdemo
    image: localhost:32000/pamdemo:latest
    ports:
      - containerPort: 22
    securityContext:
      privileged: true
    envFrom:
    - secretRef:
        name: pamdemo
---
apiVersion: v1
kind: Service
metadata:
  name: pamdemo
spec:
  ports:
    - port: 22
      targetPort: 22
      name: pamdemosvc
      protocol: TCP
      nodePort: 30222
  selector:
    app: pamdemo
  type: NodePort

